apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: sugar-suite-
nameSuffix: -latest
# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 1.1.15-28aa3ed7--2024-04-10.1712763400 # {"$imagepolicy": "sugar-suite:sugar-suite-image-policy-latest:tag"}
images:
  - name: "sugar-suite"
    newName: "registry.ltc.bcit.ca/web-apps/sugar-suite"
    newTag: "1.1.15-28aa3ed7--2024-04-10.1712763400" # {"$imagepolicy": "sugar-suite:sugar-suite-image-policy-latest:tag"}
patches:
  # Patches ingress to add "latest--" prefix to ingress URL
  #
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  # Adds secrets to deployment
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
# Appends service name to base elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=sugar-suite-latest
    behavior: merge
