apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sugar-suite
resources:
  - ../../base
commonLabels:
  environment: stable
commonAnnotations:
  version: 1.1.1 # {"$imagepolicy": "sugar-suite:sugar-suite-image-policy:tag"}
images:
  - name: "sugar-suite"
    newName: "registry.ltc.bcit.ca/web-apps/sugar-suite"
    newTag: "1.1.1" # {"$imagepolicy": "sugar-suite:sugar-suite-image-policy:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{"configMapRef": {"name":"elasticapm-config"}}]
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=sugar-suite-stable
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
