apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: sugar-suite-

resources:
  - ./nginx-unprivileged
  - ingress.yaml
  - serviceaccount.yaml

commonLabels:
  app: sugar-suite
  app.kubernetes.io/name: sugar-suite


# Patch nginx base; simplify deployment name
#
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sugar-suite
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: sugar-suite
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: sugar-suite-serviceaccount
      - op: replace
        path: /metadata/name
        value: deployment


# Generates ConfigMap resources to adjust/create base values
#
configMapGenerator:
  - name: config
    files:
      - ./nginx.conf
    behavior: replace