apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./nginx-unprivileged
  - ingress.yaml
  - serviceaccount.yaml

# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml

commonLabels:
  app: sugar-suite
  app.kubernetes.io/name: sugar-suite


# Patch nginx base; simplify deployment name
#
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sugar-suite
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: sugar-suite
      - op: replace
        path: /metadata/name
        value: deployment
  - target:
      kind: Deployment
    path: deployment-patch.yaml



# Generates ConfigMap resources to adjust/create base values
#
configMapGenerator:
  - name: config
    files:
      - ./nginx.conf
    behavior: replace

  # Generates elasticapm initial config
  #
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

