name: Course Production Pipeline CI

on:
  push:
    branches:
      - main
      - '[0-9]+-*'
permissions:
  contents: read # for checkout
  packages: write # Required for pulling images

jobs:
  semantic-release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      packages: write # Required for pushing images
    name: Run Semantic Release
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.set-version.outputs.NEXT_VERSION || '1.0.0' }}
      current-version: ${{ steps.set-version.outputs.CURRENT_VERSION || '1.0.0' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Dagger semantic release
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          args: semanticrelease --token=env://GITHUB_TOKEN

      - name: Set the version
        id: set-version
        run: |
            echo NEXT_VERSION=$(cat NEXT_VERSION) >> $GITHUB_OUTPUT
            echo CURRENT_VERSION=$(cat CURRENT_VERSION) >> $GITHUB_OUTPUT
        
          
  ## This is the step that determines the environment
  ## conditionally chooses latest, stable or review based on branch and commit
  determine-environment:
    name: Determine Environment
    needs: [semantic-release]
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit message
        id: get-commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n' | sed 's/"/\\"/g')" >> $GITHUB_ENV
      - name: Set the environment
        id: set-environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            if [[ "${{ env.COMMIT_MESSAGE }}" =~ ^(fix\s*:\s*|feat\s*:\s*|major\s*:\s*) ]]; then
              ENV_NAME="stable"
            else
              ENV_NAME="latest"
            fi
          elif [[ "${{ github.ref_name }}" =~ ^[0-9]+-.*$ ]]; then
            ENV_NAME="review"
          fi
          echo ENVIRONMENT=$ENV_NAME >> $GITHUB_OUTPUT

      - name: print the environment
        run: echo "The environment is ${{ steps.set-environment.outputs.ENVIRONMENT }}"

  build-for-environment:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      packages: write # Required for pulling images
    name: Build for environment
    needs: [determine-environment]
    if: ${{ needs.determine-environment.outputs.environment != '' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Print build environment
        run: echo "This is the ${{ needs.determine-environment.outputs.environment }} environment"
      - name: Print gathered version
        run: echo "The version is ${{ needs.semantic-release.outputs.next-version }}"
      
      - name: Create Tag
        run: |
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          CURRENT_DATE=$(date +'%Y-%m-%d')
          CURRENT_TIMESTAMP=$(date +'%s')
          ENVIRONMENT="${{ needs.determine-environment.outputs.environment }}"
          # Determine SHORT_VERSION_TAG based on the environment
          if [ "$ENVIRONMENT" == "latest" ]; then
            SHORT_VERSION_TAG="${{ needs.semantic-release.outputs.current-version }}"
          elif [ "$ENVIRONMENT" == "stable" ]; then
            SHORT_VERSION_TAG="${{ needs.semantic-release.outputs.next-version }}"
          fi
          LONG_VERSION_TAG="$SHORT_VERSION_TAG-$CURRENT_DATE--$SHORT_COMMIT.$CURRENT_TIMESTAMP"
      
          # Determine tags based on the environment
          if [ "$ENVIRONMENT" == "review" ]; then
            TAGS="review--${{ github.ref_name }}--$SHORT_COMMIT"
          elif [ "$ENVIRONMENT" == "latest" ]; then
            TAGS="$LONG_VERSION_TAG,latest"
          elif [ "$ENVIRONMENT" == "stable" ]; then
            TAGS="$SHORT_VERSION_TAG,$LONG_VERSION_TAG,latest,stable"
          fi
      
          # Export tags to GitHub environment
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo "$TAGS"
      
      - name: Build and push Docker image using Dagger
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          args: publish --registry=ghcr.io/bcit-ltc/${{ github.event.repository.name }} --username=${{ github.actor }} --token=env://GITHUB_TOKEN --tags=$TAGS