name: Run tests

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dagger run tests
      uses: dagger/dagger-for-github@8.0.0
      with:
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        call: test --source=.
