apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: app
build:
  insecureRegistries:
    - registry
  artifacts:
    - image: app
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: app
        chartPath: app-chart
        namespace: app
        createNamespace: true
        setValues:
          frontend.image.registry: registry.localhost:5000
          frontend.image.repository: app
          github.ociTokenSecretName: gh-private-oci-token
          github.ociTokenKey: GITHUB_TOKEN
        setValueTemplates:
          # frontend.image.registry: "{{.IMAGE_DOMAIN_app}}"
          # frontend.image.repository: "{{.IMAGE_REPO_NO_DOMAIN_app}}"
          frontend.image.tag: "{{.IMAGE_TAG_app}}"
    hooks:
      before:
        - host:
            command:
              - sh
              - -ceu
              - |
                : "${GITHUB_PAT:?export GITHUB_PAT=<your GitHub PAT with read:packages>}"
                : "${GITHUB_USER:?export GITHUB_USER=<your GitHub username>}"
                NS="app"

                echo "[skaffold] Preparing secrets in namespace: $NS"

                # Ensure namespace exists before creating secrets
                kubectl get ns "$NS" >/dev/null 2>&1 || kubectl create ns "$NS"

                # image pull secret for your registry
                kubectl -n "$NS" create secret docker-registry github-private-repo-token \
                  --docker-server=registry.localhost:5000 \
                  --docker-username="$GITHUB_USER" \
                  --docker-password="$GITHUB_PAT" \
                  --docker-email="devnull@example.com" \
                  --dry-run=client -o yaml | kubectl apply -f -

                # generic secret for oras login in the Job
                kubectl -n "$NS" create secret generic gh-private-oci-token \
                  --from-literal=GITHUB_TOKEN="$GITHUB_PAT" \
                  --dry-run=client -o yaml | kubectl apply -f -

# FUTURE
# - see https://skaffold.dev/docs/verify/ and https://skaffold.dev/docs/testers/structure/
# 
# profiles:
#   - name: quickcheck
#     test:
#       - image: app
#         structureTests:
#           - './test/example/container-structure-test.yaml'
# verify:
#   - name: alpine-wget
#     container:
#       name: alpine-wget
#       image: alpine:3.15.4
#       command: ["/bin/sh"]
#       args: ["-c", "wget http://www.google.com"]
# test:
#   - image: app
#     structureTests:
#       - './test/example/container-structure-test.yaml'
#     structureTestsArgs:
#       - --driver=tar
#       - -q
#       - --no-color
#       -  --test-report=TEST_REPORT_NAME